# Generated by Django 5.1.7 on 2025-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('participants', models.IntegerField(default=0, help_text='Number of participants needed or registered')),
                ('log_hour', models.FloatField(help_text='Hours to be logged for this event')),
                ('venue', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('attendance_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Close', 'Close')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
