# Generated by Django 5.1.7 on 2025-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='attendance_at',
            field=models.DateTimeField(blank=True, help_text='Punch In Time', null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='calculated_hours',
            field=models.FloatField(default=0.0, help_text='Auto-calculated hours'),
        ),
        migrations.AddField(
            model_name='participation',
            name='punch_out_at',
            field=models.DateTimeField(blank=True, help_text='Punch Out Time', null=True),
        ),
    ]
