# Generated by Django 5.1.7 on 2025-12-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participation_attendance_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='calculated_hours',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='punch_out_at',
        ),
    ]
