# Generated by Django 5.1.7 on 2026-01-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_participation_calculated_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='attendance_at',
        ),
        migrations.AddField(
            model_name='participation',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='punch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_hour',
            field=models.FloatField(blank=True, help_text='Hours to be logged for this event. Calculated automatically from start/end time if left blank.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
