# Generated by Django 5.1.7 on 2026-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_participation_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='log_hours',
            field=models.FloatField(default=0.0, help_text='Total hours logged for this session.'),
        ),
    ]
