# Generated by Django 5.1.7 on 2026-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Stored plain text password for initial login visibility', max_length=128, null=True),
        ),
    ]
